blank_issues_enabled: false

contact_links:

  - name: Question
    url: https://gis.stackexchange.com/
    about: >
      Questions should go to the mapproxy-user mailing list at https://lists.osgeo.org/mailman/listinfo/mapproxy
      or other support forums such as https://gis.stackexchange.com/.
      GitHub issues are for bug reports and suggestions for new features.

      
